#  Copyright (C) 2009 - 2009, OpenGamma.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#      http://www.apache.org/licenses/LICENSE-2.0
#      
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

TESTS=	tests\test_utilities$(SUFFIX).exe \
	tests\test_message$(SUFFIX).exe \
	tests\test_codec$(SUFFIX).exe \
	tests\test_user_types$(SUFFIX).exe

test$(SUFFIX):	tests\runtest.bat \
		$(TESTS)
	tests\runtest test_utilities$(SUFFIX)
	tests\runtest test_message$(SUFFIX)
	tests\runtest test_codec$(SUFFIX)
	tests\runtest test_user_types$(SUFFIX)

CL=cl $(CL_OPTS) $(CL_LINK_OPT) /Isrc

obj\simpletest$(SUFFIX).obj:	tests\simpletest.c \
				tests\simpletest.h \
				tests\ansi_compat.h \
				include\fudge\config.h
	$(CL) /c /Foobj\simpletest$(SUFFIX).obj tests\simpletest.c

tests\test_utilities$(SUFFIX).exe:	obj\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_utilities.c
	$(CL) /Fetests\test_utilities$(SUFFIX).exe /Foobj\test_utilities$(SUFFIX).obj tests\test_utilities.c obj\simpletest$(SUFFIX).obj libfudgec$(SUFFIX).lib wsock32.lib

tests\test_message$(SUFFIX).exe:	obj\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_message.c
        $(CL) /Fetests\test_message$(SUFFIX).exe /Foobj\test_message$(SUFFIX).obj tests\test_message.c obj\simpletest$(SUFFIX).obj libfudgec$(SUFFIX).lib wsock32.lib

tests\test_codec$(SUFFIX).exe:		obj\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_codec.c
        $(CL) /Fetests\test_codec$(SUFFIX).exe /Foobj\test_codec$(SUFFIX).obj tests\test_codec.c obj\simpletest$(SUFFIX).obj libfudgec$(SUFFIX).lib wsock32.lib

tests\test_user_types$(SUFFIX).exe:	obj\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_user_types.c
	$(CL) /Fetests\test_user_types$(SUFFIX).exe /Foobj\test_user_types$(SUFFIX).obj tests\test_user_types.c obj\simpletest$(SUFFIX).obj libfudgec$(SUFFIX).lib wsock32.lib

