#  Copyright (C) 2009 - 2009, OpenGamma.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  
#      http://www.apache.org/licenses/LICENSE-2.0
#      
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

TESTS=	tests\test_utilities$(SUFFIX).exe \
	tests\test_message$(SUFFIX).exe \
	tests\test_codec$(SUFFIX).exe \
	tests\test_user_types$(SUFFIX).exe \
	tests\test_datetime$(SUFFIX).exe \
	tests\test_string$(SUFFIX).exe

test$(SUFFIX):	tests\runtest.bat \
		$(TESTS)
	tests\runtest test_utilities$(SUFFIX)
	tests\runtest test_message$(SUFFIX)
	tests\runtest test_codec$(SUFFIX)
	tests\runtest test_user_types$(SUFFIX)
	tests\runtest test_string$(SUFFIX)
	tests\runtest test_datetime$(SUFFIX)

PROJECT_LIBRARY=$(BASENAME)$(SUFFIX).lib
CL=cl $(CL_OPTS) $(CL_LINK_OPT) /Isrc

$(OBJ_DIR)\simpletest$(SUFFIX).obj:	tests\simpletest.c \
					tests\simpletest.h \
					tests\ansi_compat.h \
					include\$(PRODUCT)\config.h
	$(CL) /c /Fo$(OBJ_DIR)\simpletest$(SUFFIX).obj tests\simpletest.c

CL=$(CL) $(PROJECT_LIBRARY) wsock32.lib

tests\test_utilities$(SUFFIX).exe:	$(OBJ_DIR)\simpletest$(SUFFIX).obj \
					$(PROJECT_LIBRARY) \
					tests\test_utilities.c
	$(CL) /Fetests\test_utilities$(SUFFIX).exe /Fo$(OBJ_DIR)\test_utilities$(SUFFIX).obj tests\test_utilities.c $(OBJ_DIR)\simpletest$(SUFFIX).obj

tests\test_message$(SUFFIX).exe:	$(OBJ_DIR)\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_message.c
        $(CL) /Fetests\test_message$(SUFFIX).exe /Fo$(OBJ_DIR)\test_message$(SUFFIX).obj tests\test_message.c $(OBJ_DIR)\simpletest$(SUFFIX).obj

tests\test_codec$(SUFFIX).exe:		$(OBJ_DIR)\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_codec.c
        $(CL) /Fetests\test_codec$(SUFFIX).exe /Fo$(OBJ_DIR)\test_codec$(SUFFIX).obj tests\test_codec.c $(OBJ_DIR)\simpletest$(SUFFIX).obj

tests\test_user_types$(SUFFIX).exe:	$(OBJ_DIR)\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_user_types.c
	$(CL) /Fetests\test_user_types$(SUFFIX).exe /Fo$(OBJ_DIR)\test_user_types$(SUFFIX).obj tests\test_user_types.c $(OBJ_DIR)\simpletest$(SUFFIX).obj

tests\test_datetime$(SUFFIX).exe:	$(OBJ_DIR)\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_datetime.c
	$(CL) /Fetests\test_datetime$(SUFFIX).exe /Fo$(OBJ_DIR)\test_datetime$(SUFFIX).obj tests\test_datetime.c $(OBJ_DIR)\simpletest$(SUFFIX).obj

tests\test_string$(SUFFIX).exe:		$(OBJ_DIR)\simpletest$(SUFFIX).obj \
					libfudgec$(SUFFIX).lib \
					tests\test_string.c
	$(CL) /Fetests\test_string$(SUFFIX).exe /Fo$(OBJ_DIR)\test_string$(SUFFIX).obj tests\test_string.c $(OBJ_DIR)\simpletest$(SUFFIX).obj
